#!/bin/bash

case "$1" in

-h )
	S=$(date +%s.%N)
	N=0
	for FILE in content/tex/*.tex
	do
		./helper -t $(basename $FILE)
		N=$((N+1))
	done
	D=$(echo "$(date +%s.%N) - $S" | bc)

	echo "Done: Processed $N LaTeX articles to Markdown in $(printf "%0.2f\n" $D) seconds."
	;;
-t ) 
	if [ -z ${2+x} ] 
	then 
		S=$(date +%s.%N)
		N=0
		for FILE in content/tex/*.tex
		do
			BASE=$(basename $FILE)
			IN=content/tex/$BASE
			OUT=content/posts/${BASE%%.tex}.md
			LOG=content/tex/${BASE%%.tex}.pre

			DIN=$(stat -c %Y $IN)

			if [ -f $OUT ]
			then
				DOUT=$(stat -c %Y $OUT)
			else
				DOUT=0
			fi

			if [ $DOUT -lt $DIN  ]
			then
				simpleL2M -i $IN | pandoc -f latex -t markdown >> $LOG
				cat $LOG > $OUT
				N=$((N+1))
			fi
		done
		D=$(echo "$(date +%s.%N) - $S" | bc)
		if [ $N -eq 0 ]
		then
			echo "Done: Nothing to convert all Markdown up-to-date"
		else
			echo "Done: Converted $N LaTeX article(s) to Markdown in $(printf "%0.2f\n" $D) seconds."
		fi
	else
		IN=content/tex/$2
		OUT=content/posts/${2%%.tex}.md
		LOG=content/tex/${2%%.tex}.pre
		if [ -f $IN ]
		then 
			DIN=$(stat -c %Y $IN)
			DOUT=$(stat -c %Y $OUT)
			if [ $DOUT -lt $DIN  ]
			then
				simpleL2M -i $IN | pandoc -f latex -t markdown >> $LOG
				cat $LOG > $OUT
			else
				echo "$OUT es más nuevo que $IN"
			fi
		else
			echo "El archivo no existe."
			exit 1
    		fi
	fi
    	;;
-n )  
	if [ -z ${2+x} ] 
	then 
		echo "-n necesita parametro";
	else
		OUT=content/posts/$2
		if [ -f $OUT ]
		then
			echo "El archivo ya existe."
			exit 1
		else
			echo "Title: " > $OUT
			echo "Date: $(date +%Y-%M-%D)" >> $OUT
			echo "Category: Blog" >> $OUT
			echo "Tags: " >> $OUT
			echo "Slug: " >> $OUT
			echo "Summary: " >> $OUT
			echo "Status: draft" >> $OUT
			echo  "MD file created: $OUT"
		fi
	fi
    	;;
-c )  
	echo  "Publish and double commiting";
	if [ -z ${2+x} ] 
	then 
		echo "-c necesita parametro";
	else
		MSG=$2

		make publish
		cd output
		git add .
		git commit -m "$MSG"
		read -p "push?(Yy): " answer
		if [[ "$answer" == [Yy] ]]
		then
			git push			
		fi

		cd ..
		git add .
		git commit -m "$MSG"
	fi
     	;;
*) 
	echo "WTH!";
	;;
esac
